/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Instalador;

import Control.Control;
import com.alee.laf.WebLookAndFeel;
import Control.Entrada;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import static java.lang.Math.floor;
import java.net.URI;
import java.net.URISyntaxException;
import static test.test.CargarBat;

/**
 *
 * @author Microinformatica
 */
public class Inicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Acceder
     */
    private final Image img;

    public Inicio1() {
        initComponents();

        this.setLocationRelativeTo(null);
        img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/facelet/icon.png"));
        setIconImage(img);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container01 = new javax.swing.JPanel();
        alerta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BackBox");
        setBackground(java.awt.Color.white);
        setResizable(false);
        setState(6);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        container01.setBackground(new java.awt.Color(255, 255, 255));
        container01.setMinimumSize(new java.awt.Dimension(791, 491));
        container01.setName(""); // NOI18N
        container01.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        container01.add(alerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 110, 40));

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("INICIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        container01.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 500));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facelet/img001_opt.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 0, 72, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Java");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 450, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Instalaciones");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Base de Datos.");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jButton2.setText("Instalar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, 40));

        jButton3.setText("Instalar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        container01.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container01, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized
    public static void CargarBat(String comando) {
        try {
            String linea;
            Process p = Runtime.getRuntime().exec(comando);
            BufferedReader input = new BufferedReader(new InputStreamReader(p.getInputStream()));
            while ((linea = input.readLine()) != null) {
                System.out.println(linea);
            }
            input.close();
        } catch (Exception err) {
            err.printStackTrace();
        }
    }

    public void DatosNecesarios() {
        try {
            Control.conectar();
            //Datos Regimen
            Control.ejecuteUpdate("Insert into regimen values(1,'Regimen Simplificado')");
            Control.ejecuteUpdate("Insert into regimen values(2,'Regimen Comun')");
            //Datos Acciones
            Control.ejecuteUpdate("insert into acciones values(	1	,'Lista Usuarios')	");
            Control.ejecuteUpdate("insert into acciones values(	2	,'Crear Usuario')	");
            Control.ejecuteUpdate("insert into acciones values(	3	,'Linea')	");
            Control.ejecuteUpdate("insert into acciones values(	4	,'Lista Bodega')	");
            Control.ejecuteUpdate("insert into acciones values(	5	,'Lista Proveedores')	");
            Control.ejecuteUpdate("insert into acciones values(	6	,'Crear Proveedor')	");
            Control.ejecuteUpdate("insert into acciones values(	7	,'Lista Rol')	");
            Control.ejecuteUpdate("insert into acciones values(	8	,'Crear Rol')	");
            Control.ejecuteUpdate("insert into acciones values(	9	,'Ver Articulos')	");
            Control.ejecuteUpdate("insert into acciones values(	10	,'Nueva Compra')	");
            Control.ejecuteUpdate("insert into acciones values(	11	,'Ver Categoria')	");
            Control.ejecuteUpdate("insert into acciones values(	12	,'Crear Categoria')	");
            Control.ejecuteUpdate("insert into acciones values(	14	,'Realiza Compra')	");
            Control.ejecuteUpdate("insert into acciones values(	16	,'Realizar Venta')	");
            Control.ejecuteUpdate("insert into acciones values(	17	,'Realizar Devolucion')	");
            Control.ejecuteUpdate("insert into acciones values(	18	,'Ver Venta Diaria')	");
            Control.ejecuteUpdate("insert into acciones values(	19	,'Reportes')	");
            Control.ejecuteUpdate("insert into acciones values(	20	,'Venta')	");
            Control.ejecuteUpdate("insert into acciones values(	21	,'Compras')	");
            Control.ejecuteUpdate("insert into acciones values(	22	,'Entrada y Salidas')	");
            Control.ejecuteUpdate("insert into acciones values(	23	,'Ayuda en Linea')	");
            Control.ejecuteUpdate("insert into acciones values(	24	,'BackBox')	");
            Control.ejecuteUpdate("insert into acciones values(	25	,'Atajos')	");
            Control.ejecuteUpdate("insert into acciones values(	26	,'Acerca De')	");
            Control.ejecuteUpdate("insert into acciones values(	27	,'Inicio')	");
            Control.ejecuteUpdate("insert into acciones values(	28	,'Cerrar Sesion')	");
            Control.ejecuteUpdate("insert into acciones values(	29	,'Salir')	");
            Control.ejecuteUpdate("insert into acciones values(	30	,'Lista Clientes')	");
            Control.ejecuteUpdate("insert into acciones values(	31	,'Nuevo Clientes')	");
            //Datos Actividad
            Control.ejecuteUpdate("	insert into actividades values(	1	,'Bodega',	2	)	");
            Control.ejecuteUpdate("	insert into actividades values(	2	,'Ventas',	5	)	");
            Control.ejecuteUpdate("	insert into actividades values(	3	,'Reportes',	4	)	");
            Control.ejecuteUpdate("	insert into actividades values(	4	,'Ayuda',	6	)	");
            Control.ejecuteUpdate("	insert into actividades values(	5	,'Archivo',	1	)	");
            Control.ejecuteUpdate("	insert into actividades values(	18	,'Stakeholders',	3	)	");

            //Datos Rol
            Control.ejecuteUpdate("	insert into actividades values(	1,'Administrador','A')");

            //Datos Detalle Actividad
            Control.ejecuteUpdate("	insert into detalleactividad values(	1	,	1	,	1	,	4	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	2	,	1	,	1	,	3	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	3	,	1	,	1	,	9	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	4	,	1	,	1	,	10	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	5	,	1	,	1	,	3	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	6	,	1	,	1	,	11	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	7	,	1	,	1	,	12	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	8	,	1	,	1	,	3	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	9	,	18	,	1	,	1	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	10	,	18	,	1	,	2	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	11	,	18	,	1	,	3	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	12	,	2	,	1	,	16	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	13	,	2	,	1	,	17	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	14	,	2	,	1	,	18	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	15	,	2	,	1	,	3	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	16	,	3	,	1	,	20	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	17	,	3	,	1	,	21	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	18	,	3	,	1	,	22	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	19	,	3	,	1	,	3	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	20	,	18	,	1	,	5	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	21	,	18	,	1	,	6	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	22	,	18	,	1	,	3	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	23	,	18	,	1	,	7	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	24	,	18	,	1	,	8	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	25	,	18	,	1	,	3	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	26	,	18	,	1	,	30	)	");
            Control.ejecuteUpdate("	insert into detalleactividad values(	27	,	18	,	1	,	3	)	");

            //Tipo de Venta
            Control.ejecuteUpdate("Insert into tipo_venta values(1,'Venta')");
            Control.ejecuteUpdate("Insert into tipo_venta values(2,'Devolucion')");

            //Tipo de Pago
            Control.ejecuteUpdate("Insert into tipopago values(1,'Efectivo')");
            Control.ejecuteUpdate("Insert into tipopago values(2,'Tarjeta Credito')");

        } catch (Exception ex) {

        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        String cmd = "C:\\Program Files\\PostgreSQL\\9.4\\scripts\\runpsql.bat";
//        CargarBat(cmd);
        new Registro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String cmd = "C:\\Users\\admin\\Documents\\ProyectoInventarius\\BackBox - Instalador\\src\\Inicio.bat";
        CargarBat(cmd);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String cmd = "C:\\Users\\admin\\Documents\\ProyectoInventarius\\BackBox - Instalador\\src\\IntalacionJDK.bat";
        CargarBat(cmd);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alerta;
    private javax.swing.JPanel container01;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
