/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vw.components;

import Modelo.Producto;
import Control.Control;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author Britany
 */
public class Detalle_Entrada extends javax.swing.JFrame {

    /**
     * Creates new form Articulo
     */
    String cod;
    String nom;
    String provedor;
    String fecha;
    Connection cone;
    ArrayList<Integer> ListAcciones = new ArrayList();

    public Detalle_Entrada(String cod, String nom, String fecha) throws ClassNotFoundException {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/facelet/icon.png")));
        this.setLocationRelativeTo(null);
        this.cod = cod;
        this.inicio();
        this.recuperarDatos();
    }

    private void recuperarDatos() throws ClassNotFoundException {
        Control.conectar();
        try {
            Control.ejecuteQuery("select distinct  detalle.factura ,provedor.empresa,sum(detalle.costo)from provedor,detalle where \n"
                    + "provedor.cod_provedor=detalle.provedor\n"
                    + "group by\n"
                    + "detalle.factura ,provedor.empresa");

            while (Control.rs.next()) {
                factura.setText("Factura :      " + Control.rs.getString(1));
                provedor = Control.rs.getString(2);
                proveedor.setText("Empresa :      " + Control.rs.getString(2));
                total.setText("Total :        " + Control.rs.getString(3));
            }
            Control.cerrarConexion();
        } catch (Exception ex) {

        } finally {
            Control.cerrarConexion();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        centro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        superior = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        factura = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        proveedor = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        inferior = new javax.swing.JPanel();
        imprimir = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Salir = new javax.swing.JButton();
        derecha = new javax.swing.JPanel();
        izquierda = new javax.swing.JPanel();

        jButton3.setText("Nuevo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detalle de Compras - BackBox");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        centro.setBackground(new java.awt.Color(255, 255, 255));
        centro.setLayout(new javax.swing.BoxLayout(centro, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setViewportView(jTable1);

        centro.add(jScrollPane1);

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        superior.setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        factura.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        factura.setText("Factura:");
        factura.setMaximumSize(new java.awt.Dimension(300, 30));
        factura.setMinimumSize(new java.awt.Dimension(300, 30));
        factura.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel1.add(factura);
        jPanel1.add(jSeparator1);

        proveedor.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        proveedor.setText("Empresa:");
        proveedor.setMaximumSize(new java.awt.Dimension(300, 25));
        proveedor.setMinimumSize(new java.awt.Dimension(300, 25));
        proveedor.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel1.add(proveedor);
        jPanel1.add(jSeparator2);

        superior.add(jPanel1);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        total.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        total.setText("Total:");
        total.setMaximumSize(new java.awt.Dimension(250, 25));
        total.setMinimumSize(new java.awt.Dimension(250, 25));
        total.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel2.add(total);

        superior.add(jPanel2);

        getContentPane().add(superior, java.awt.BorderLayout.PAGE_START);

        inferior.setBackground(java.awt.Color.white);
        inferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        imprimir.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        imprimir.setText("Imprimir");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });
        inferior.add(imprimir);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(160, 40));
        jSeparator3.setRequestFocusEnabled(false);
        inferior.add(jSeparator3);

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-xhdpi/ic_arrow_back_black_24dp.png"))); // NOI18N
        Salir.setBorder(null);
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salir.setPreferredSize(new java.awt.Dimension(55, 47));
        Salir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        inferior.add(Salir);

        getContentPane().add(inferior, java.awt.BorderLayout.PAGE_END);

        derecha.setBackground(java.awt.Color.white);
        getContentPane().add(derecha, java.awt.BorderLayout.LINE_END);

        izquierda.setBackground(java.awt.Color.white);
        getContentPane().add(izquierda, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed

        Reporte_Entradas m;
        try {
            m = new Reporte_Entradas(nom, ListAcciones);
            this.dispose();
            m.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Detalle_Entrada.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_SalirActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        try {
            Control.conectar();
            cone = Control.con;
            generarFactura(cone);
            Control.cerrarConexion();
        } catch (ClassNotFoundException | JRException ex) {
            Logger.getLogger(Detalle_Entrada.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_imprimirActionPerformed
    public void generarFactura(Connection c) throws JRException, ClassNotFoundException {
        try {
            HashMap<String, Object> parametros = new HashMap<String, Object>();
            parametros.put("Cod_fac", cod);
            parametros.put("fec_fac", fecha);
            parametros.put("provedor", provedor);
            JasperReport report = JasperCompileManager.compileReport("FacCompra.jrxml");
            JasperPrint jasperPrint = JasperFillManager.fillReport(report, parametros, c);
            JasperPrintManager.printReport(jasperPrint, true);
            //JasperPrintManager.printReport(jasperPrint, true);
        } catch (Exception ex) {
            System.err.println(ex.toString());
        }
    }

    private void inicio() throws ClassNotFoundException {
        Control.conectar();
        Producto temp = null;
        String query = "select producto.cod_producto \"Codigo\""
                + ",nombre \"Nombre\",detalle.costo \"Costo\""
                + ",detalle.cantidad \"Cantidad\" from detalle,producto\n"
                + "                where \n"
                + "                detalle.cod_producto=producto.cod_producto and\n"
                + "               detalle.factura='" + cod + "'";
        String cod = "", nom = "", valor = "", cant = "", costo = "", iva = "", precio = "";
        String cate = "";
        DefaultTableModel modeloEmpleado = new DefaultTableModel();
        int numeroPreguntas;
        ResultSetMetaData rsetMetaData;
        this.jTable1.setModel(modeloEmpleado);
        try {
            boolean r = Control.ejecuteQuery(query);

            rsetMetaData = Control.rs.getMetaData();
            numeroPreguntas = rsetMetaData.getColumnCount();
            //Establece los nombres de las columnas de las tablas
            for (int i = 0; i < numeroPreguntas; i++) {
                modeloEmpleado.addColumn(rsetMetaData.getColumnLabel(i + 1));
            }

            while (Control.rs.next()) {
                cod = Control.rs.getString(1);
                nom = Control.rs.getString(2);
                costo = Control.rs.getString(3);
                cant = Control.rs.getString(4);

                Object[] registroEmpleado = new Object[numeroPreguntas];

                for (int i = 0; i < numeroPreguntas; i++) {
                    registroEmpleado[i] = Control.rs.getObject(i + 1);
                }
                modeloEmpleado.addRow(registroEmpleado);
            }
            Control.cerrarConexion();
//            Control.rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR " + e.getMessage());
        } finally {
            Control.cerrarConexion();
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel derecha;
    private javax.swing.JLabel factura;
    private javax.swing.JButton imprimir;
    private javax.swing.JPanel inferior;
    private javax.swing.JPanel izquierda;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel proveedor;
    private javax.swing.JPanel superior;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
