/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vw.components;

import Modelo.Producto;
import Control.Control;
import Modelo.exportar_excel;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import vw.dialogs.ReporteDetalleCompra;
import vw.main.Menu;
//com.alee.extended.date.WebDateField

/**
 *
 * @author Britany
 */
public class Reporte_Entradas extends javax.swing.JFrame {

    /**
     * Creates new form Articulo
     */
    String usuario;
    ArrayList<Integer> ListAcciones = new ArrayList();

    public Reporte_Entradas(String nom, ArrayList acciones) throws ClassNotFoundException {
        initComponents();
        this.usuario = nom;
        this.ListAcciones = acciones;
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/facelet/icon.png")));
        Date fecha = new Date();
        fechaInicial.setDate(fecha);
        jDateChooser2.setDate(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        centro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        superior = new javax.swing.JPanel();
        fechaIni = new javax.swing.JLabel();
        fechaInicial = new com.alee.extended.date.WebDateField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser2 = new com.alee.extended.date.WebDateField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        inferior = new javax.swing.JPanel();
        ingIzq = new javax.swing.JPanel();
        txtTotal = new javax.swing.JLabel();
        totaltext = new javax.swing.JLabel();
        infDer = new javax.swing.JPanel();
        detalle = new javax.swing.JButton();
        expPDF = new javax.swing.JButton();
        expXLSX = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        volver = new javax.swing.JButton();

        jButton3.setText("Nuevo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte Entradas - BackBox");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        centro.setBackground(new java.awt.Color(255, 255, 255));
        centro.setLayout(new java.awt.BorderLayout(0, 5));

        jScrollPane1.setViewportView(jTable1);

        centro.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        superior.setBackground(java.awt.Color.white);
        superior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        fechaIni.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        fechaIni.setText("Fecha Inicial:");
        superior.add(fechaIni);

        fechaInicial.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        fechaInicial.setMinimumSize(new java.awt.Dimension(130, 30));
        fechaInicial.setPreferredSize(new java.awt.Dimension(130, 30));
        superior.add(fechaInicial);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator4.setPreferredSize(new java.awt.Dimension(30, 30));
        jSeparator4.setRequestFocusEnabled(false);
        superior.add(jSeparator4);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Fecha Final:");
        superior.add(jLabel3);

        jDateChooser2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jDateChooser2.setMinimumSize(new java.awt.Dimension(130, 30));
        jDateChooser2.setPreferredSize(new java.awt.Dimension(130, 30));
        superior.add(jDateChooser2);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(160, 30));
        jSeparator3.setRequestFocusEnabled(false);
        superior.add(jSeparator3);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-mdpi/ic_find_in_page_black_24dp.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        superior.add(jButton1);

        getContentPane().add(superior, java.awt.BorderLayout.PAGE_START);

        inferior.setBackground(java.awt.Color.white);
        inferior.setLayout(new java.awt.GridLayout(1, 0));

        ingIzq.setBackground(java.awt.Color.lightGray);
        ingIzq.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtTotal.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        txtTotal.setText("Total:");
        ingIzq.add(txtTotal);

        totaltext.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        totaltext.setForeground(new java.awt.Color(255, 153, 0));
        totaltext.setMaximumSize(new java.awt.Dimension(9999, 48));
        totaltext.setMinimumSize(new java.awt.Dimension(290, 48));
        totaltext.setPreferredSize(new java.awt.Dimension(290, 48));
        ingIzq.add(totaltext);

        inferior.add(ingIzq);

        infDer.setBackground(java.awt.Color.white);
        infDer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        detalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-mdpi/ic_assignment_black_24dp.png"))); // NOI18N
        detalle.setText("Detalle");
        detalle.setBorder(null);
        detalle.setBorderPainted(false);
        detalle.setContentAreaFilled(false);
        detalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detalle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        detalle.setPreferredSize(new java.awt.Dimension(55, 47));
        detalle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        detalle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalleActionPerformed(evt);
            }
        });
        infDer.add(detalle);

        expPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facelet/pdf.jpg"))); // NOI18N
        expPDF.setBorder(null);
        expPDF.setBorderPainted(false);
        expPDF.setContentAreaFilled(false);
        expPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expPDFActionPerformed(evt);
            }
        });
        infDer.add(expPDF);

        expXLSX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-xhdpi/export_to_excel_24dp.png"))); // NOI18N
        expXLSX.setBorder(null);
        expXLSX.setBorderPainted(false);
        expXLSX.setContentAreaFilled(false);
        expXLSX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expXLSX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        expXLSX.setPreferredSize(new java.awt.Dimension(55, 47));
        expXLSX.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        expXLSX.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        expXLSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expXLSXActionPerformed(evt);
            }
        });
        infDer.add(expXLSX);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(150, 40));
        jSeparator2.setRequestFocusEnabled(false);
        infDer.add(jSeparator2);

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-xhdpi/ic_arrow_back_black_24dp.png"))); // NOI18N
        volver.setBorder(null);
        volver.setBorderPainted(false);
        volver.setContentAreaFilled(false);
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        volver.setPreferredSize(new java.awt.Dimension(55, 47));
        volver.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        volver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        infDer.add(volver);

        inferior.add(infDer);

        getContentPane().add(inferior, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        new Menu(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            inicio();
        } catch (Exception ex) {

        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalleActionPerformed
        int i = jTable1.getSelectedRow();
        int j = jTable1.getSelectedColumn();
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "Favor... seleccione una fila");
        } else {
            Date date = fechaInicial.getDate();
            SimpleDateFormat format2 = new SimpleDateFormat("yyyy_MM-dd");
            String fecha = format2.format(date);
            String cod = (String) jTable1.getValueAt(i, 0).toString();
            String total = (String) jTable1.getValueAt(i, 2).toString();
            ReporteDetalleCompra de;
            try {
                de = new ReporteDetalleCompra(this, true, fecha, cod, total);
                de.setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Reporte_Entradas.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_detalleActionPerformed

    private void expXLSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expXLSXActionPerformed
        if (jTable1.getRowCount() >= 1) {
            getBto_exportar();
        } else {
            JOptionPane.showMessageDialog(null, "No hay Datos Para Exportar");
        }


    }//GEN-LAST:event_expXLSXActionPerformed
    public void generarCompraPDF() throws JRException, ClassNotFoundException {

        try {
            Date date = fechaInicial.getDate();
            SimpleDateFormat format2 = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = format2.format(date);

            Date date2 = jDateChooser2.getDate();
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String fechaF = format.format(date2);
            String query = "";

            query = "select distinct c.factura \"Factura\" ,a.cod_producto \"Producto\",a.nombre \"Descripcion\",c.costo \"Costo\",c.cantidad \"cantidad\",b.empresa \n"
                    + "\"Proveedor\",b.nit \"Nit\",to_char(c.fecha_entrada, 'dd-mm-yyyy') \"fecha\" from detalle c ,provedor b ,producto a where \n"
                    + "b.cod_provedor=c.provedor\n"
                    + "and  c.cod_producto=a.cod_producto\n"
                    + "and c.fecha_entrada between  '" + fecha.substring(0, 10).concat(" 00:00:00'") + " and '"
                    + fechaF.substring(0, 10).concat(" 23:59:59'")
                    + "group by\n"
                    + "c.factura,b.empresa,b.nit,a.cod_producto,a.nombre,c.costo,c.cantidad,c.fecha_entrada\n"
                    + "order by c.factura,a.cod_producto";
            System.out.println("" + query);
            Control.conectar();
            HashMap<String, Object> parametros = new HashMap<String, Object>();
            parametros.put("fechaI", fecha);
            parametros.put("FechaF", fechaF);
            parametros.put("query", query);
            JasperReport report = JasperCompileManager.compileReport("Rep_FacturasCompradas.jrxml");
            System.out.println("--- : " + report.getName());
            JasperPrint jasperPrint = JasperFillManager.fillReport(report, parametros, Control.con);
            JasperViewer.viewReport(jasperPrint, false);
            //JasperPrintManager.printReport(jasperPrint, true);
            Control.cerrarConexion();
        } catch (Exception ex) {
            System.err.println(ex.toString());
        }
    }
    private void expPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expPDFActionPerformed
        try {
            System.out.println("------------- : COMPRAPDF");
            generarCompraPDF();
        } catch (JRException ex) {
            Logger.getLogger(Reporte_Ventas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reporte_Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_expPDFActionPerformed
    private void getBto_exportar() {
        try {
            /**
             * ****************AGREGO EL JTABLA A UN
             * ARRAYLIST**************************
             */
            List<JTable> tb = new ArrayList<JTable>();
            tb.add(jTable1);
            //-------------------
            exportar_excel excelExporter = new exportar_excel(tb, new File("DATOS_EXPORTADOS.xls"));
            if (excelExporter.export()) {
                JOptionPane.showMessageDialog(null, "DATOS EXPORTADOS CON EXITO!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        llama_excel();

    }

    public void llama_excel() {
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "DATOS_EXPORTADOS.xls");
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    public void inicio() throws ClassNotFoundException {
        Control.conectar();
        DecimalFormat formateador = new DecimalFormat("###,###.##");
        Date date = fechaInicial.getDate();
        SimpleDateFormat format2 = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = format2.format(date);

        Date date2 = jDateChooser2.getDate();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String fecha2 = format.format(date2);

        Producto temp = null;
        String query = "select distinct detalle.factura \"Factura\""
                + ",provedor.empresa \"Proveedor\""
                + ",sum(detalle.costo)\"Total\",\n"
                + "sum(detalle.cantidad)\"Cantidad\" from detalle,provedor where \n"
                + "provedor.cod_provedor=detalle.provedor\n"
                + "and detalle.fecha_entrada between '" + fecha.substring(0, 10).concat(" 00:00:00") + "' and '"
                + fecha2.substring(0, 10).concat(" 23:59:59'")
                + " group by\n"
                + "detalle.factura,provedor.empresa\n"
                + "order by sum(detalle.costo) DESC";
        String cod = "", nom = "", valor = "", cant = "", costo = "", iva = "", precio = "";
        String cate = "";
        DefaultTableModel modeloEmpleado = new DefaultTableModel();
        int numeroPreguntas;
        ResultSetMetaData rsetMetaData;
        this.jTable1.setModel(modeloEmpleado);
        try {
            boolean r = Control.ejecuteQuery(query);

            rsetMetaData = Control.rs.getMetaData();
            numeroPreguntas = rsetMetaData.getColumnCount();
            //Establece los nombres de las columnas de las tablas
            for (int i = 0; i < numeroPreguntas; i++) {
                modeloEmpleado.addColumn(rsetMetaData.getColumnLabel(i + 1));
            }
            double total = 0;
            while (Control.rs.next()) {
                cod = Control.rs.getString(1);
                nom = Control.rs.getString(2);
                costo = Control.rs.getString(3);
                cant = Control.rs.getString(4);
                total = total + Double.parseDouble(costo);
                Object[] registroEmpleado = new Object[numeroPreguntas];

                for (int i = 0; i < numeroPreguntas; i++) {
                    registroEmpleado[i] = Control.rs.getObject(i + 1);
                }
                modeloEmpleado.addRow(registroEmpleado);
            }
            Control.cerrarConexion();
            this.totaltext.setText("" + formateador.format(total));
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ERROR " + e.getMessage());
        } finally {
            Control.cerrarConexion();
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centro;
    private javax.swing.JButton detalle;
    private javax.swing.JButton expPDF;
    private javax.swing.JButton expXLSX;
    private javax.swing.JLabel fechaIni;
    private com.alee.extended.date.WebDateField fechaInicial;
    private javax.swing.JPanel infDer;
    private javax.swing.JPanel inferior;
    private javax.swing.JPanel ingIzq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private com.alee.extended.date.WebDateField jDateChooser2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel superior;
    private javax.swing.JLabel totaltext;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
