/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vw.components;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import vw.main.Menu;
import vw.main.Acceder;
import vw.model.Venta;
import vw.model.Articulo;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import vw.dialogs.AcercaDe;
import vw.dialogs.CategoriasRegistrar;
import vw.dialogs.ProveedoresRegistrar;
import vw.dialogs.RolRegistrar;
import vw.dialogs.UsuariosRegistrar;

/**
 *
 * @author Microinformatica
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Bodega
     */
    String usuario;
    ArrayList<Integer> ListAcciones = new ArrayList();

    public Reportes(String nom, ArrayList acciones) {
        initComponents();
        this.usuario = nom;
        this.ListAcciones = acciones;
        MenuDinamico();
        this.setLocationRelativeTo(null);
        setTitle("GALVISOFT REPORTES");
        this.setResizable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/facelet/icon.png")));
    }

    public void MenuDinamico() {
//        jMenuItem6.setVisible(false);
//        jMenuItem7.setVisible(false);
//        jMenuItem8.setVisible(false);
//        jMenuItem9.setVisible(false);
//        jMenuItem10.setVisible(false);
//        jMenuItem12.setVisible(false);
//        jMenuItem11.setVisible(false);
//        jMenuItem3.setVisible(false);
//        jMenuItem4.setVisible(false);
//        jMenuItem5.setVisible(false);
//        for (Integer ListAccione : ListAcciones) {
//            if (ListAccione == 1) {
//                jMenuItem6.setVisible(true);
//            } else if (ListAccione == 6) {
//                jMenuItem7.setVisible(true);
//                jMenuItem8.setVisible(true);
//            } else if (ListAccione == 9) {
//                jMenuItem9.setVisible(true);
//                jMenuItem10.setVisible(true);
//            } else if (ListAccione == 13) {
//                jMenuItem12.setVisible(true);
//            } else if (ListAccione == 14) {
//                jMenuItem11.setVisible(true);
//            } else if (ListAccione == 18) {
//                jMenuItem3.setVisible(true);
//                jMenuItem4.setVisible(true);
//            } else if (ListAccione == 22) {
//                jMenuItem5.setVisible(true);
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        inicio = new javax.swing.JMenuItem();
        cerrarSesion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        user = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        crearUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        listaProveerdores = new javax.swing.JMenuItem();
        crearProveedor = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        listaRoles = new javax.swing.JMenuItem();
        crearRol = new javax.swing.JMenuItem();
        stok = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        bill = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        realizarVenta = new javax.swing.JMenuItem();
        realizarDevolucion = new javax.swing.JMenuItem();
        verVentaDiaria = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        reporteVentas = new javax.swing.JMenuItem();
        ReporteCompras = new javax.swing.JMenuItem();
        reporteEYS = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        ayudaLinea = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        paginaWeb = new javax.swing.JMenuItem();
        atajos = new javax.swing.JMenuItem();
        aboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-xhdpi/ic_arrow_back_black_24dp.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-xxxhdpi/ic_archive_gray_24dp.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-xxxhdpi/ic_view_list_gray_24dp.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-xxxhdpi/ic_shopping_cart_gray_24dp.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(54, 54, 54)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        file.setText("Archivo");
        file.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        inicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        inicio.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        inicio.setText("Inicio");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        file.add(inicio);

        cerrarSesion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        file.add(cerrarSesion);
        file.add(jSeparator1);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        salir.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        file.add(salir);

        jMenuBar1.add(file);

        user.setText("Gestionar Cuentas");
        user.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem3.setText("Lista Usuarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        user.add(jMenuItem3);

        crearUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        crearUsuario.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        crearUsuario.setText("Crear Usuario");
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });
        user.add(crearUsuario);
        user.add(jSeparator2);

        listaProveerdores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        listaProveerdores.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        listaProveerdores.setText("Lista Proveedores");
        listaProveerdores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaProveerdoresActionPerformed(evt);
            }
        });
        user.add(listaProveerdores);

        crearProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        crearProveedor.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        crearProveedor.setText("Crear Proveedor");
        crearProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearProveedorActionPerformed(evt);
            }
        });
        user.add(crearProveedor);
        user.add(jSeparator5);

        listaRoles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        listaRoles.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        listaRoles.setText("Lista Roles");
        listaRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaRolesActionPerformed(evt);
            }
        });
        user.add(listaRoles);

        crearRol.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        crearRol.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        crearRol.setText("Crear Rol");
        crearRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearRolActionPerformed(evt);
            }
        });
        user.add(crearRol);

        jMenuBar1.add(user);

        stok.setText("Bodega");
        stok.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jMenuItem6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem6.setText("Lista Bodega");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        stok.add(jMenuItem6);
        stok.add(jSeparator3);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem7.setText("Ver Artículos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        stok.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem8.setText("Nuevo artículo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        stok.add(jMenuItem8);
        stok.add(jSeparator4);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem9.setText("Ver Categorías");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        stok.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem10.setText("Crear Categoría");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        stok.add(jMenuItem10);

        jMenuBar1.add(stok);

        bill.setText("Transacciones");
        bill.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem2.setText("Entradas y Salidas");
        bill.add(jMenuItem2);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem1.setText("Realizar Compra");
        bill.add(jMenuItem1);

        jMenu6.setText("Ventas y Devoluciones");
        jMenu6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        realizarVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        realizarVenta.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        realizarVenta.setText("Realizar Venta");
        realizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVentaActionPerformed(evt);
            }
        });
        jMenu6.add(realizarVenta);

        realizarDevolucion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        realizarDevolucion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        realizarDevolucion.setText("Realizar Devolución");
        realizarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarDevolucionActionPerformed(evt);
            }
        });
        jMenu6.add(realizarDevolucion);

        verVentaDiaria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        verVentaDiaria.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        verVentaDiaria.setText("Ver Ventas del Día");
        verVentaDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verVentaDiariaActionPerformed(evt);
            }
        });
        jMenu6.add(verVentaDiaria);

        bill.add(jMenu6);
        bill.add(jSeparator7);

        jMenu5.setText("Reportes");
        jMenu5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        reporteVentas.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        reporteVentas.setText("Ventas");
        reporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteVentasActionPerformed(evt);
            }
        });
        jMenu5.add(reporteVentas);

        ReporteCompras.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        ReporteCompras.setText("Compras");
        ReporteCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteComprasActionPerformed(evt);
            }
        });
        jMenu5.add(ReporteCompras);

        reporteEYS.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        reporteEYS.setText("Entradas y Salidas");
        reporteEYS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteEYSActionPerformed(evt);
            }
        });
        jMenu5.add(reporteEYS);

        bill.add(jMenu5);

        jMenuBar1.add(bill);

        help.setText("Ayuda");
        help.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        ayudaLinea.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        ayudaLinea.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        ayudaLinea.setText(" Ayuda en línea");
        ayudaLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaLineaActionPerformed(evt);
            }
        });
        help.add(ayudaLinea);
        help.add(jSeparator6);

        paginaWeb.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        paginaWeb.setText("BackBox");
        paginaWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paginaWebActionPerformed(evt);
            }
        });
        help.add(paginaWeb);

        atajos.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        atajos.setText("Atajos");
        atajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atajosActionPerformed(evt);
            }
        });
        help.add(atajos);

        aboutUs.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        aboutUs.setText("Acerca de...");
        aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsActionPerformed(evt);
            }
        });
        help.add(aboutUs);

        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Menu(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        Reporte_Entradas re;
        try {
            re = new Reporte_Entradas(usuario, ListAcciones);
            this.setVisible(false);
            re.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String op[] = new String[2];
        op[0] = "1";
        op[1] = "2";
        int cod = Entrada.menu("REPORTE SALIDAS Y ENTRADAS ", "1: Por Fecha \n2: Por Producto", op);
        if (cod == 2) {
            Salida_Entrada_P sal;
            try {
                sal = new Salida_Entrada_P(usuario, ListAcciones);
                this.setVisible(false);
                sal.setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                DatallesPorFecha fec = new DatallesPorFecha(usuario, ListAcciones);
                this.dispose();
                fec.setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Reporte_Ventas v;
        try {
            v = new Reporte_Ventas(usuario, ListAcciones);
            this.dispose();
            v.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reportes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        new Menu(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inicioActionPerformed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed

        this.dispose();
        new Acceder().setVisible(true);

    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            new Usuarios(usuario, ListAcciones).setVisible(true);;
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bodega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        new UsuariosRegistrar(this, true).setVisible(true);
    }//GEN-LAST:event_crearUsuarioActionPerformed

    private void listaProveerdoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaProveerdoresActionPerformed
        try {
            new Provedores(usuario, ListAcciones).setVisible(true);;
            this.dispose();;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listaProveerdoresActionPerformed

    private void crearProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearProveedorActionPerformed
        new ProveedoresRegistrar(this, true).setVisible(true);
    }//GEN-LAST:event_crearProveedorActionPerformed

    private void listaRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaRolesActionPerformed
        try {
            new Roles(usuario, ListAcciones).setVisible(true);;
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listaRolesActionPerformed

    private void crearRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearRolActionPerformed
        new RolRegistrar(this, true).setVisible(true);
    }//GEN-LAST:event_crearRolActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Bodega b = new Bodega(usuario, ListAcciones);
            this.dispose();
            b.setVisible(true);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Articulo ar;
        try {
            ar = new Articulo(usuario, ListAcciones);
            this.dispose();
            ar.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bodega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Entrada_Nueva rp;
        try {
            ArrayList<Producto> pr = new ArrayList();
            String fac = "";
            rp = new Entrada_Nueva(pr, usuario, fac, ListAcciones);
            rp.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Articulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            new CategoriaGestion(usuario, ListAcciones).setVisible(true);
            this.dispose();
        } catch (Exception x) {
            /*Nothig Here*/
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new CategoriasRegistrar(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void realizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVentaActionPerformed
        ArrayList<Producto> productos = new ArrayList();
        try {
            new Venta(productos, usuario, 1, ListAcciones).setVisible(true);;
            this.setVisible(false);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_realizarVentaActionPerformed

    private void realizarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarDevolucionActionPerformed
        ArrayList<Producto> pro = new ArrayList();
        try {
            new Venta(pro, usuario, 2, ListAcciones).setVisible(true);;
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_realizarDevolucionActionPerformed

    private void verVentaDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verVentaDiariaActionPerformed

        try {
            new VentaDiaria(usuario, ListAcciones).setVisible(true);;
            this.dispose();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_verVentaDiariaActionPerformed

    private void reporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteVentasActionPerformed
        try {
            new Reporte_Ventas(usuario, ListAcciones).setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_reporteVentasActionPerformed

    private void ReporteComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteComprasActionPerformed
        try {
            new Reporte_Entradas(usuario, ListAcciones).setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_ReporteComprasActionPerformed

    private void reporteEYSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteEYSActionPerformed
        /*Esperando metodo*/
    }//GEN-LAST:event_reporteEYSActionPerformed

    private void ayudaLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaLineaActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI("http://www.qmanager.com.co"));
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ayudaLineaActionPerformed

    private void paginaWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paginaWebActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI("http://www.qmanager.com.co"));
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_paginaWebActionPerformed

    private void atajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atajosActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI("http://www.qmanager.com.co"));
            } catch (URISyntaxException | IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_atajosActionPerformed

    private void aboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsActionPerformed
        new AcercaDe(this, true).setVisible(true);
    }//GEN-LAST:event_aboutUsActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ReporteCompras;
    private javax.swing.JMenuItem aboutUs;
    private javax.swing.JMenuItem atajos;
    private javax.swing.JMenuItem ayudaLinea;
    private javax.swing.JMenu bill;
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JMenuItem crearProveedor;
    private javax.swing.JMenuItem crearRol;
    private javax.swing.JMenuItem crearUsuario;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JMenuItem inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JMenuItem listaProveerdores;
    private javax.swing.JMenuItem listaRoles;
    private javax.swing.JMenuItem paginaWeb;
    private javax.swing.JMenuItem realizarDevolucion;
    private javax.swing.JMenuItem realizarVenta;
    private javax.swing.JMenuItem reporteEYS;
    private javax.swing.JMenuItem reporteVentas;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenu stok;
    private javax.swing.JMenu user;
    private javax.swing.JMenuItem verVentaDiaria;
    // End of variables declaration//GEN-END:variables
}
