/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vw.main;

import Control.Control;
import Control.Entrada;
import com.alee.laf.WebLookAndFeel;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import vw.dialogs.AcercaDe;

/**
 *
 * @author Miguel Lemoz
 */
public class Acceder extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public Acceder() {
        initComponents();
        initComponentsCustom();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/facelet/icon.png")));
        probarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPpal = new javax.swing.JPanel();
        centro = new javax.swing.JPanel();
        field01 = new org.edisoncor.gui.textField.TextFieldRectBackground();
        field02 = new org.edisoncor.gui.passwordField.PasswordFieldRectBackground();
        text04 = new javax.swing.JLabel();
        text03 = new javax.swing.JLabel();
        text02 = new javax.swing.JLabel();
        acceder = new javax.swing.JLabel();
        text01 = new javax.swing.JLabel();
        text05 = new javax.swing.JLabel();
        text06 = new javax.swing.JLabel();
        alerta = new javax.swing.JLabel();
        derecha = new javax.swing.JPanel();
        izquierda = new javax.swing.JPanel();
        img001 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        atajos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        homaPage = new javax.swing.JMenuItem();
        aboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a BackBox");
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 600));

        contenedorPpal.setBackground(java.awt.Color.white);
        contenedorPpal.setLayout(new java.awt.BorderLayout());

        centro.setBackground(java.awt.Color.white);

        field01.setBackground(new java.awt.Color(254, 254, 254));
        field01.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        field01.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        field01.setToolTipText("Ingrese su nombre de Usuario");
        field01.setDescripcion("Ingrese Usuario");
        field01.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        field01.setMargin(new java.awt.Insets(3, 3, 3, 3));
        field01.setPreferredSize(new java.awt.Dimension(160, 30));

        field02.setBackground(new java.awt.Color(254, 254, 254));
        field02.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        field02.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        field02.setToolTipText("Ingrese su clave de usuario");
        field02.setDescripcion("Ingrese Clave");
        field02.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        field02.setMargin(new java.awt.Insets(3, 3, 3, 3));
        field02.setPreferredSize(new java.awt.Dimension(160, 30));
        field02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field02ActionPerformed(evt);
            }
        });

        text04.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        text04.setText("Contraseña:");

        text03.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        text03.setText("Nombre de Usuario:");

        text02.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        text02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text02.setText("guardar todo en la Caja");
        text02.setPreferredSize(new java.awt.Dimension(194, 41));

        acceder.setBackground(new java.awt.Color(153, 153, 153));
        acceder.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        acceder.setForeground(new java.awt.Color(255, 255, 255));
        acceder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceder.setText("Acceder");
        acceder.setToolTipText("Ingresa al sistema");
        acceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceder.setOpaque(true);
        acceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accederMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accederMouseExited(evt);
            }
        });

        text01.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        text01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text01.setText("Ingresa para ");
        text01.setPreferredSize(new java.awt.Dimension(194, 41));

        text05.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        text05.setForeground(java.awt.Color.red);
        text05.setText("**Este Campo es requerido");

        text06.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        text06.setForeground(java.awt.Color.red);
        text06.setText("**Este Campo es requerido");

        alerta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout centroLayout = new javax.swing.GroupLayout(centro);
        centro.setLayout(centroLayout);
        centroLayout.setHorizontalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(acceder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(centroLayout.createSequentialGroup()
                        .addComponent(text03)
                        .addGap(0, 242, Short.MAX_VALUE))
                    .addComponent(text06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        centroLayout.setVerticalGroup(
            centroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(text01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text06)
                .addGap(39, 39, 39)
                .addComponent(text04)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text05)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acceder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alerta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contenedorPpal.add(centro, java.awt.BorderLayout.CENTER);

        derecha.setBackground(java.awt.Color.white);
        contenedorPpal.add(derecha, java.awt.BorderLayout.LINE_END);

        izquierda.setBackground(new java.awt.Color(196, 70, 38));
        izquierda.setLayout(new javax.swing.BoxLayout(izquierda, javax.swing.BoxLayout.LINE_AXIS));

        img001.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facelet/img001.png"))); // NOI18N
        img001.setPreferredSize(new java.awt.Dimension(250, 200));
        izquierda.add(img001);

        contenedorPpal.add(izquierda, java.awt.BorderLayout.LINE_START);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Salir.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenu2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        help.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        help.setText(" Ayuda en línea");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jMenu2.add(help);
        jMenu2.add(jSeparator2);

        atajos.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        atajos.setText("Atajos");
        atajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atajosActionPerformed(evt);
            }
        });
        jMenu2.add(atajos);
        jMenu2.add(jSeparator1);

        homaPage.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        homaPage.setText("Pagina de Inico");
        homaPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homaPageActionPerformed(evt);
            }
        });
        jMenu2.add(homaPage);

        aboutUs.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        aboutUs.setText("Acerca de...");
        aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsActionPerformed(evt);
            }
        });
        jMenu2.add(aboutUs);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contenedorPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(contenedorPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponentsCustom() {
        alerta.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        alerta.setText("jLabel4");
    }

    private void probarConexion() {
        text05.setVisible(false);
        text06.setVisible(false);
        try {
            if (Control.conectar()) {
                alerta.setText("Conectado...");
                alerta.setForeground(Color.green);
            } else {
                alerta.setText("Sin Conexión...");
                alerta.setForeground(Color.lightGray);
                Entrada.muestreMensajeV("No hay Conecion a la Base de Datos Comunicarse con soporte");
            }
        } catch (ClassNotFoundException ex) {
            System.out.println("Error:" + ex.toString());
        } finally {
            Control.cerrarConexion();
        }
    }

    private void validarUsuario() throws ClassNotFoundException {
        if (field01.getText().isEmpty() | field02.getText().isEmpty()) {
            text05.setVisible(true);
            text06.setVisible(true);
        } else {
            Control.conectar();
            try {
                boolean r = Control.ejecuteQuery("select "
                        + "rol.cod_rol,"
                        + "persona.nombre, "
                        + "persona.apellido,usuario.cod_usuario "
                        + "from usuario,rol,persona\n"
                        + "where\n"
                        + "usuario.cod_rol=rol.cod_rol and\n"
                        + "persona.cedula=usuario.cedula\n"
                        + "and usuario.usuario=lower('" + field01.getText() + "') and\n"
                        + " usuario.clave=lower('" + field02.getText() + "')");
                int rol = 0;
                String Usuario = "";
                String Usu = "";
                boolean f = false;

                while (Control.rs.next()) {
                    rol = Control.rs.getInt(1);
                    Usuario = Control.rs.getString(2) + " " + Control.rs.getString(3);
                    Usu = Control.rs.getString(4);
                    f = true;
                }
                if (f) {
                    if (rol >= 1) {
                        Menu newMenu = new Menu(Usu);
                        newMenu.setVisible(true);
                        this.setVisible(false);
                    }
                } else {
                    Entrada.muestreMensajeV("El usuario o la clave no son correctos",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                System.out.println("Error: " + ex.toString());
            } finally {
                Control.cerrarConexion();
            }
        }
    }

    private void field02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field02ActionPerformed
        try {
            validarUsuario();
        } catch (Exception ex) {
            //Nothing Here
        }
    }//GEN-LAST:event_field02ActionPerformed

    private void accederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederMouseClicked
        try {
            validarUsuario();
        } catch (Exception ex) {
            //Nothing Here
        }
    }//GEN-LAST:event_accederMouseClicked

    private void accederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederMouseEntered
        acceder.setBackground(new Color(196, 70, 38));
    }//GEN-LAST:event_accederMouseEntered

    private void accederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederMouseExited
        acceder.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_accederMouseExited

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            try {
                java.awt.Desktop dk = java.awt.Desktop.getDesktop();
                dk.browse(new URI("https://github.com/UnlimitedDreams/ProyectoInventarius/wiki/1.-Ayuda"));
            } catch (URISyntaxException | IOException e) {
                System.out.println("Error al abrir URL: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_helpActionPerformed

    private void atajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atajosActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            try {
                java.awt.Desktop dk = java.awt.Desktop.getDesktop();
                dk.browse(new URI("https://github.com/UnlimitedDreams/ProyectoInventarius/wiki/1.-Ayuda"));
            } catch (URISyntaxException | IOException e) {
                System.out.println("Error al abrir URL: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_atajosActionPerformed

    private void homaPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homaPageActionPerformed
        if (java.awt.Desktop.isDesktopSupported()) {
            try {
                java.awt.Desktop dk = java.awt.Desktop.getDesktop();
                dk.browse(new URI("https://github.com/UnlimitedDreams/ProyectoInventarius/wiki/0.-Inicio"));
            } catch (URISyntaxException | IOException e) {
                System.out.println("Error al abrir URL: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_homaPageActionPerformed

    private void aboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsActionPerformed
        new AcercaDe(this, true).setVisible(true);
    }//GEN-LAST:event_aboutUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            WebLookAndFeel.install();
            new Acceder().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem aboutUs;
    private javax.swing.JLabel acceder;
    private javax.swing.JLabel alerta;
    private javax.swing.JMenuItem atajos;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel contenedorPpal;
    private javax.swing.JPanel derecha;
    private org.edisoncor.gui.textField.TextFieldRectBackground field01;
    private org.edisoncor.gui.passwordField.PasswordFieldRectBackground field02;
    private javax.swing.JMenuItem help;
    private javax.swing.JMenuItem homaPage;
    private javax.swing.JLabel img001;
    private javax.swing.JPanel izquierda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel text01;
    private javax.swing.JLabel text02;
    private javax.swing.JLabel text03;
    private javax.swing.JLabel text04;
    private javax.swing.JLabel text05;
    private javax.swing.JLabel text06;
    // End of variables declaration//GEN-END:variables
}
