/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vw.main;

import Control.Control;
import com.alee.laf.WebLookAndFeel;
import vw.components.Buscar;
import vw.components.Entrada;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.lang.Math.floor;
import vw.dialogs.AcercaDe;
import vw.model.Venta;

/**
 *
 * @author Microinformatica
 */
public class Acceder extends javax.swing.JFrame {

    /**
     * Creates new form Acceder
     */
    private final Image img;

    public Acceder() {
        initComponents();
        initComponentsCustom();
        this.setLocationRelativeTo(null);
        img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/facelet/icon.png"));
        setIconImage(img);
        probarConexion();

    }

    public void probarConexion() {
        try {
            if (Control.conectar()) {
                alerta.setText("Conectado...");
                alerta.setForeground(Color.green);
            } else {
                alerta.setText("Sin Conexión...");
                alerta.setForeground(Color.lightGray);
                Entrada.muestreMensajeV("No hay Conecion a la Base de Datos Comunicarse con soporte");
            }
        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(Acceder.class.getName()).log(Level.SEVERE, null, "-------------"+ex);
        }
    }

    private void initComponentsCustom() {
        alerta = new javax.swing.JLabel();
        alerta.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        alerta.setText("jLabel4");
        panel.add(alerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(
                (int) floor((this.getSize().width * 0.7) + 130),
                (int) floor((this.getSize().height * 0.80) + 20), 130, 20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        social01 = new javax.swing.JLabel();
        social02 = new javax.swing.JLabel();
        acceder = new javax.swing.JButton();
        field01 = new org.edisoncor.gui.textField.TextFieldRectBackground();
        field02 = new org.edisoncor.gui.passwordField.PasswordFieldRectBackground();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label02 = new javax.swing.JLabel();
        label01 = new javax.swing.JLabel();
        label03 = new javax.swing.JLabel();
        alerta = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        atajos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        aboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceder - BackBox");
        setBackground(java.awt.Color.white);
        setResizable(false);
        setState(6);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setMinimumSize(new java.awt.Dimension(791, 491));
        panel.setName(""); // NOI18N
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        social01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-mdpi/ic_share_black_24dp.png"))); // NOI18N
        social01.setToolTipText("Compartir");
        social01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel.add(social01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        social02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-mdpi/ic_plus_one_black_24dp.png"))); // NOI18N
        social02.setToolTipText("Google+");
        social02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel.add(social02, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        acceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-hdpi/acceder_48dp.png"))); // NOI18N
        acceder.setBorder(null);
        acceder.setBorderPainted(false);
        acceder.setContentAreaFilled(false);
        acceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        acceder.setPreferredSize(new java.awt.Dimension(59, 30));
        acceder.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drawable-hdpi/acceder_rollover_48dp.png"))); // NOI18N
        acceder.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        acceder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederActionPerformed(evt);
            }
        });
        panel.add(acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        field01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field01.setToolTipText("Ingrese su número de cedula");
        field01.setDescripcion("Ingrese Usuario");
        field01.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        field01.setPreferredSize(new java.awt.Dimension(160, 30));
        panel.add(field01, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));
        field01.getAccessibleContext().setAccessibleName("");

        field02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field02.setDescripcion("Ingrese Clave");
        field02.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        field02.setPreferredSize(new java.awt.Dimension(160, 30));
        field02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field02ActionPerformed(evt);
            }
        });
        panel.add(field02, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        jPanel1.setBackground(new java.awt.Color(196, 70, 38));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facelet/img001.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 510));

        label02.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        label02.setText("Contraseña");
        panel.add(label02, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        label01.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        label01.setText("Usuario");
        panel.add(label01, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        label03.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        label03.setText("Guarda todo en la Caja");
        label03.setPreferredSize(new java.awt.Dimension(194, 41));
        panel.add(label03, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 350, -1));
        panel.add(alerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 110, 40));

        jMenuBar1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Salir.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenu1.add(Salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenu2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem1.setText(" Ayuda en línea");
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator2);

        atajos.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        atajos.setText("Atajos");
        jMenu2.add(atajos);
        jMenu2.add(jSeparator1);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jMenuItem3.setText("Pagina de Inico");
        jMenu2.add(jMenuItem3);

        aboutUs.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        aboutUs.setText("Acerca de...");
        aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsActionPerformed(evt);
            }
        });
        jMenu2.add(aboutUs);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        panel.setSize(this.getSize());
        panel.setLayout(panel.getLayout());
    }//GEN-LAST:event_formComponentResized

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederActionPerformed
        try {
            validarUsuario();
        } catch (Exception ex) {
            //Nothing Here
        }
    }//GEN-LAST:event_accederActionPerformed

    private void field02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field02ActionPerformed
        accederActionPerformed(evt);
    }//GEN-LAST:event_field02ActionPerformed

    private void aboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsActionPerformed
        new AcercaDe(this, true).setVisible(true);
    }//GEN-LAST:event_aboutUsActionPerformed

    public void validarUsuario() throws ClassNotFoundException {
        Control.conectar();
        boolean r = Control.ejecuteQuery("select "
                + "rol.cod_rol,"
                + "persona.nombre, "
                + "persona.apellido,usuario.cod_usuario "
                + "from usuario,rol,persona\n"
                + "where\n"
                + "usuario.cod_rol=rol.cod_rol and\n"
                + "persona.cedula=usuario.cedula\n"
                + "and usuario.usuario=lower('" + field01.getText() + "') and\n"
                + " usuario.clave=lower('" + field02.getText() + "')");
        System.out.println("Ejecuto consulta: " + r);
        int rol = 0;
        String Usuario = "";
        String Usu = "";
        boolean f = false;
        try {
            while (Control.rs.next()) {
                rol = Control.rs.getInt(1);
                Usuario = Control.rs.getString(2) + " " + Control.rs.getString(3);
                Usu = Control.rs.getString(4);
                f = true;
            }
            Control.cerrarConexion();
            System.out.println("Usuario : " + Usu);
            if (f) {
                if (rol >= 1) {
                    Menu newMenu = new Menu(Usu);
                    newMenu.setVisible(true);
                    this.setVisible(false);
                } else {
//                    Venta newBuscar = new Venta(Usuario);
//                    newBuscar.setVisible(true);
//                    this.setVisible(false);
                }
            } else {
                Entrada.muestreMensajeV("El usuario o la clave no son correctos",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Acceder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
            public void run() {
                WebLookAndFeel.install();
                new Acceder().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem aboutUs;
    private javax.swing.JButton acceder;
    private javax.swing.JLabel alerta;
    private javax.swing.JMenuItem atajos;
    private org.edisoncor.gui.textField.TextFieldRectBackground field01;
    private org.edisoncor.gui.passwordField.PasswordFieldRectBackground field02;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel label01;
    private javax.swing.JLabel label02;
    private javax.swing.JLabel label03;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel social01;
    private javax.swing.JLabel social02;
    // End of variables declaration//GEN-END:variables
}
