/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vw.help;

import Control.Control;
import java.net.URL;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Miguel Lemoz
 */
public class Ayudas extends javax.swing.JFrame {

    /**
     * Creates new form Ayudas
     *
     * @param codigo
     */
    TreeMap ayudasPrimerNivel = new TreeMap();
    TreeMap ayudasSegundoNivel = new TreeMap();

    public Ayudas(int codigo) {
        initComponents();
        crearArbol();
        listaAyudas.setSelectionRow(0);
        URL url = getClass().getResource("/images/facelet/icon.png");
        ImageIcon img = new ImageIcon(url);
        setIconImage(img.getImage());
        this.setLocationRelativeTo(null);
    }

    private void crearArbol() {
        TreeMap arbolPrincipal = new TreeMap();
        DefaultMutableTreeNode carpetaRaiz = new DefaultMutableTreeNode("Inicio");
        DefaultTreeModel modelo = new DefaultTreeModel(carpetaRaiz);
        listaAyudas.setModel(modelo);
        try {
            Control.conectar();
            Control.ejecuteQuery("SELECT idvista, nombre, ayuda\n"
                    + "  FROM helps.vistas;");
            while (Control.rs.next()) {
                arbolPrincipal.put(Control.rs.getInt(1), Control.rs.getString(2));
                ayudasPrimerNivel.put(Control.rs.getInt(1), Control.rs.getString(3));
            }
            for (Iterator iterator = arbolPrincipal.entrySet().iterator(); iterator.hasNext();) {
                Map.Entry me = (Map.Entry) iterator.next();
                int key = (int) me.getKey();
                DefaultMutableTreeNode temp = new DefaultMutableTreeNode(key + "." + arbolPrincipal.get(key));
                modelo.insertNodeInto(temp, carpetaRaiz, key - 1);
                Control.ejecuteQuery("SELECT idayuda, idvista, nombre, index, ayuda\n"
                        + "  FROM helps.ayudas\n"
                        + "  where idvista= " + key + ";");
                while (Control.rs.next()) {
                    ayudasSegundoNivel.put(key + "." + Control.rs.getInt(4), Control.rs.getString(5));
                    modelo.insertNodeInto(new DefaultMutableTreeNode(key + "." + Control.rs.getInt(4) + "." + Control.rs.getString(3)),
                            temp,
                            Control.rs.getInt(4) - 1);
                }
            }
        } catch (ClassNotFoundException | SQLException classNotFoundException) {
            System.out.println("Error:" + classNotFoundException.toString());
        } finally {
            Control.cerrarConexion();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        listado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAyudas = new javax.swing.JTree();
        ayuda = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ayudaTextual = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BackBox - Ayudas");
        setPreferredSize(new java.awt.Dimension(560, 560));
        setResizable(false);

        principal.setBackground(java.awt.Color.white);

        listaAyudas.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        listaAyudas.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                listaAyudasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaAyudas);

        javax.swing.GroupLayout listadoLayout = new javax.swing.GroupLayout(listado);
        listado.setLayout(listadoLayout);
        listadoLayout.setHorizontalGroup(
            listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );
        listadoLayout.setVerticalGroup(
            listadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        ayuda.setBackground(new java.awt.Color(196, 70, 38));
        ayuda.setForeground(new java.awt.Color(196, 70, 38));
        ayuda.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        ayuda.setPreferredSize(new java.awt.Dimension(382, 540));

        titulo.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        titulo.setForeground(java.awt.Color.lightGray);
        titulo.setText("Ayudas");

        ayudaTextual.setEditable(false);
        ayudaTextual.setColumns(20);
        ayudaTextual.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ayudaTextual.setRows(5);
        ayudaTextual.setBorder(null);
        ayudaTextual.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(ayudaTextual);

        javax.swing.GroupLayout ayudaLayout = new javax.swing.GroupLayout(ayuda);
        ayuda.setLayout(ayudaLayout);
        ayudaLayout.setHorizontalGroup(
            ayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ayudaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ayudaLayout.setVerticalGroup(
            ayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ayudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                .addComponent(listado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ayuda, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addComponent(listado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaAyudasValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_listaAyudasValueChanged
        if (Arrays.toString(listaAyudas.getSelectionRows()).equals("[0]")) {
            ayudaTextual.setText("\n"
                    + "\n"
                    + "\n"
                    + "Bienvenido al sistema de ayudas\n"
                    + "Para más info visitenos en: \n"
                    + "www.BackBox.com");
        } else {

//            TreePath path;
            String[] temp = evt.getPath().getLastPathComponent().toString().split(Pattern.quote("."));

            if (temp.length < 3) {
                ayudaTextual.setText(ayudasPrimerNivel.get(Integer.parseInt(temp[0])).toString());
            } else {
                System.out.println(evt.getPath());
                ayudaTextual.setText(ayudasSegundoNivel.get(temp[0] + "." + temp[1]).toString());
//                ayudaTextual.setText(evt.getPath() + " \n"
//                        + Arrays.toString(listaAyudas.getSelectionRows()));
            }
        }
    }//GEN-LAST:event_listaAyudasValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayudas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ayudas(1).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ayuda;
    private javax.swing.JTextArea ayudaTextual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree listaAyudas;
    private javax.swing.JPanel listado;
    private javax.swing.JPanel principal;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
